import React, { useEffect, useRef, useState } from 'react';
import { FlatList, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { useFocusEffect } from '@react-navigation/native';
import { COLORS, RADIUS, SHADOW } from '../theme';
import PrimaryButton from '../components/PrimaryButton';
import CenteredMessage from '../components/CenteredMessage';
import { clearStagingPhoto, getRecords, getStagingPhoto, setStagingPhoto } from '../storage';

export default function CameraScreen() {
  const [permission, requestPermission] = useCameraPermissions(); const cameraRef = useRef(null); const [photo, setPhoto] = useState(null); const [facing, setFacing] = useState('back'); const [records, setRecords] = useState([]);
  useEffect(() => { getStagingPhoto().then(setPhoto); }, []);
  useFocusEffect(React.useCallback(() => { getRecords().then(setRecords); }, []));
  if (!permission) return <CenteredMessage text="Verificando permissão da câmera..." />;
  if (!permission.granted) return <SafeAreaView style={styles.screen} edges={['top', 'left', 'right']}><Text style={styles.kicker}>COMPROVANTES SALVOS</Text><Text style={styles.title}>Comprovantes</Text><Text style={styles.subtitle}>Os comprovantes são fotografados dentro do cadastro de manutenção.</Text><View style={styles.permissionCard}><Text style={styles.permissionIcon}>▣</Text><Text style={styles.permissionTitle}>A câmera será aberta na manutenção</Text><Text style={styles.permissionText}>Ao criar uma nova manutenção, toque em “Foto comprovante”.</Text></View><PrimaryButton title="Permitir acesso à câmera" onPress={requestPermission} /></SafeAreaView>;
  async function takePicture() { if (!cameraRef.current) return; const result = await cameraRef.current.takePictureAsync({ quality: 0.8 }); if (result?.uri) { setPhoto(result.uri); await setStagingPhoto(result.uri); } }
  async function retake() { setPhoto(null); await clearStagingPhoto(); }
  const saved = records.filter((item) => item.photo);
  return <SafeAreaView style={styles.screen} edges={['top', 'left', 'right']}><FlatList data={saved} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.kicker}>COMPROVANTES SALVOS</Text><Text style={styles.title}>Comprovantes</Text><Text style={styles.subtitle}>Aqui ficam as fotos vinculadas às manutenções já salvas. Para um novo comprovante, use a aba Manutenções.</Text>{photo && <View style={styles.stagingCard}><Image source={{ uri: photo }} style={styles.stagingImage} /><Text style={styles.savedText}>Foto pronta para a próxima manutenção</Text><PrimaryButton title="Remover foto provisória" variant="secondary" onPress={retake} /></View>}<Text style={styles.sectionTitle}>Histórico de comprovantes</Text></>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyIcon}>▣</Text><Text style={styles.emptyTitle}>Nenhum comprovante salvo</Text><Text style={styles.emptyText}>As fotos aparecerão aqui depois que uma manutenção for salva.</Text></View>} renderItem={({ item }) => <View style={styles.savedCard}><Image source={{ uri: item.photo }} style={styles.thumb} /><View style={styles.savedBody}><Text style={styles.savedTitle}>{item.description}</Text><Text style={styles.savedMeta}>{item.vehicle || 'Veículo não informado'} • {item.date}</Text></View></View>} /></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: COLORS.bg }, content: { padding: 20, paddingBottom: 35 }, kicker: { color: COLORS.blue, fontSize: 11, fontWeight: '900', letterSpacing: 1.4, marginTop: 12 }, title: { color: COLORS.text, fontSize: 28, fontWeight: '900', marginTop: 4 }, subtitle: { color: COLORS.muted, fontSize: 14, lineHeight: 21, marginTop: 7, marginBottom: 15 }, permissionCard: { backgroundColor: COLORS.card, borderRadius: RADIUS.card, padding: 23, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', marginTop: 12, marginBottom: 18, ...SHADOW }, permissionIcon: { color: COLORS.blue, fontSize: 37 }, permissionTitle: { color: COLORS.text, fontSize: 17, fontWeight: '900', textAlign: 'center', marginTop: 12 }, permissionText: { color: COLORS.muted, fontSize: 13, textAlign: 'center', lineHeight: 19, marginTop: 7 }, stagingCard: { backgroundColor: COLORS.card, borderRadius: RADIUS.card, padding: 12, marginBottom: 18, borderWidth: 1, borderColor: COLORS.blue }, stagingImage: { width: '100%', height: 180, borderRadius: 12, resizeMode: 'contain', backgroundColor: '#10202A' }, savedText: { color: COLORS.green, fontWeight: '800', fontSize: 13, marginVertical: 10 }, sectionTitle: { color: COLORS.text, fontSize: 16, fontWeight: '900', marginBottom: 10 }, savedCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.card, borderRadius: 14, padding: 10, borderWidth: 1, borderColor: COLORS.border, marginBottom: 9 }, thumb: { width: 70, height: 70, borderRadius: 10, backgroundColor: '#10202A', marginRight: 11 }, savedBody: { flex: 1 }, savedTitle: { color: COLORS.text, fontSize: 15, fontWeight: '900' }, savedMeta: { color: COLORS.muted, fontSize: 12, marginTop: 5 }, empty: { backgroundColor: COLORS.card, borderRadius: 15, padding: 24, alignItems: 'center', borderWidth: 1, borderColor: COLORS.border }, emptyIcon: { color: COLORS.blue, fontSize: 32 }, emptyTitle: { color: COLORS.text, fontSize: 16, fontWeight: '900', marginTop: 8 }, emptyText: { color: COLORS.muted, textAlign: 'center', lineHeight: 19, fontSize: 13, marginTop: 5 } });
